Repository lifinance/contracts, pull requests merged in 2025-04, with the labels that each got.

#1084 Deploy MayanFacet 1.2.0 to all supported chains
  deployments/_deployments_log_file.json
  deployments/arbitrum.diamond.staging.json
  deployments/arbitrum.json
  deployments/arbitrum.staging.json
  deployments/avalanche.json
  deployments/base.json
  deployments/bsc.json
  deployments/mainnet.json
  deployments/optimism.json
  deployments/polygon.json
  deployments/unichain.json
Labels: AuditNotRequired

#1085 Redeploy RelayFacet on ApeChain
  config/relay.json
  deployments/_deployments_log_file.json
  deployments/apechain.json
Labels: AuditNotRequired

#1082 feat(whitelist): update zerox route address on AVA
  config/dexs.json
Labels: AuditNotRequired

#1088 archive unused config file
  archive/config/tokenwrapper.json
Labels: AuditNotRequired

#1092 Deploy new network: corn
  .env.example
  .github/workflows/diamondEmergencyPause.yml
  config/dexs.json
  config/gaszip.json
  config/networks.json
  config/permit2Proxy.json
  config/relay.json
  deployments/_deployments_log_file.json
  deployments/corn.diamond.json
  deployments/corn.json
  foundry.toml
  script/deploy/_targetState.json
  script/tasks/diamondUpdateFacet.sh
  test/solidity/Facets/ChainflipFacet.t.sol
Labels: AuditNotRequired

#1098 feat: allow new enso contracts
  config/dexs.json
  config/sigs.json
Labels: AuditNotRequired

#1099 feat: whiltelist apechain openocean dexs router
  config/dexs.json
Labels: AuditNotRequired

#1069 deployed ThorswapFacet to Base
  config/thorswap.json
  deployments/_deployments_log_file.json
  deployments/base.diamond.json
  deployments/base.json
Labels: AuditNotRequired

#1083 LF-12882 - Added increment on currently allowed dex in loop [DexManagerFacet v1.0.2]
  audit/auditLog.json
  audit/reports/2025.04.13_DexManagerFacet(v1.0.2).pdf
  src/Facets/DexManagerFacet.sol
  test/solidity/Facets/DexManagerFacet.t.sol
Labels: AuditCompleted, AuditRequired

#1080 LF-12880 Added new error case [Permit2Proxy v1.0.3]
  audit/auditLog.json
  audit/reports/2025.04.15_Permit2Proxy(v1.0.3).pdf
  src/Periphery/Permit2Proxy.sol
  test/solidity/Periphery/Permit2Proxy.t.sol
Labels: AuditCompleted, waitForAudit, AuditRequired

#1101 deploy Mayan to linea
  config/mayan.json
  deployments/_deployments_log_file.json
  deployments/linea.diamond.json
  deployments/linea.json
Labels: AuditNotRequired

#1100 ReceiverStargateV2 redeployed to kaia
  config/stargateV2.json
  deployments/_deployments_log_file.json
  deployments/kaia.diamond.json
  deployments/kaia.json
Labels: AuditNotRequired

#1110 config: add 0x addresses on new chains
  config/dexs.json
Labels: AuditNotRequired

#1109 Deploy RelayFacet to Worldchain
  deployments/_deployments_log_file.json
  deployments/worldchain.diamond.json
  deployments/worldchain.json
Labels: AuditNotRequired

#1108 diamond log updated
  deployments/zksync.diamond.json
  deployments/zksync.json
Labels: AuditNotRequired

#1093 Deploy to Lens
  .github/workflows/diamondEmergencyPause.yml
  .gitignore
  archive/config/tokenwrapper.json
  config/across.json
  config/dexs.json
  config/gaszip.json
  config/networks.json
  deployments/_deployments_log_file.json
  deployments/lens.diamond.json
  deployments/lens.json
  foundry.toml
  script/deploy/_targetState.json
  script/deploy/deploySingleContract.sh
  script/deploy/healthCheck.ts
  script/deploy/zksync/DeployAccessManagerFacet.zksync.s.sol
  script/deploy/zksync/UpdateAcrossFacetPackedV3.zksync.s.sol
  script/deploy/zksync/UpdateAcrossFacetV3.zksync.s.sol
  script/deploy/zksync/UpdateCoreFacets.zksync.s.sol
  script/deploy/zksync/UpdateGasZipFacet.zksync.s.sol
  script/helperFunctions.sh
  script/tasks/diamondUpdateFacet.sh
Labels: AuditNotRequired

#1087 Deploy new network: swellchain
  .env.example
  .github/workflows/diamondEmergencyPause.yml
  archive/config/tokenwrapper.json
  config/dexs.json
  config/gaszip.json
  config/networks.json
  config/permit2Proxy.json
  config/relay.json
  deployments/_deployments_log_file.json
  deployments/swellchain.diamond.json
  deployments/swellchain.json
  foundry.toml
  script/deploy/_targetState.json
Labels: AuditNotRequired

#1086 LF-13019 LiFiDexAggregator to support Velodrome v2 [IVelodromeV2Pool v1.0.0,IVelodromeV2PoolCallee v1.0.0,IVelodromeV2PoolFactory v1.0.0,IVelodromeV2Router v1.0.0,LiFiDEXAggregator v1.8.0]
  .github/workflows/enforceTestCoverage.yml
  .github/workflows/forge.yml
  audit/auditLog.json
  audit/reports/2025.04.11_LiFiDEXAggregator(v1.7.0).pdf
  audit/reports/2025.04.22_LiFiDexAggregator(v1.8.0).pdf
  src/Interfaces/IVelodromeV2Pool.sol
  src/Interfaces/IVelodromeV2PoolCallee.sol
  src/Interfaces/IVelodromeV2PoolFactory.sol
  src/Interfaces/IVelodromeV2Router.sol
  src/Periphery/LiFiDEXAggregator.sol
  test/solidity/Periphery/LiFiDEXAggregator.t.sol
  test/solidity/utils/TestBase.sol
Labels: AuditCompleted, AuditRequired

#1112 deployed symbiosis to soneium
  config/symbiosis.json
  deployments/_deployments_log_file.json
  deployments/soneium.diamond.json
  deployments/soneium.json
Labels: AuditNotRequired

#1102 optimized sync-sigs script to run networks in parallel
  script/helperFunctions.sh
  script/tasks/diamondSyncDEXs_FAST.sh
  script/tasks/diamondSyncSigs_FAST.sh
Labels: AuditNotRequired

#1058 LF-12743 Create fix for gaszipfacet [GasZipFacet v2.0.3]
  audit/auditLog.json
  audit/reports/2025.04.16_GasZipFacet(v2.0.3).pdf
  deployments/_deployments_log_file.json
  deployments/arbitrum.diamond.staging.json
  deployments/arbitrum.staging.json
  script/demoScripts/demoGasZip.ts
  script/demoScripts/utils/demoScriptHelpers.ts
  src/Facets/GasZipFacet.sol
  test/solidity/Facets/GasZipFacet.t.sol
Labels: AuditCompleted, AuditRequired

#1111 Update apechain Etherscan API URL in foundry.toml
  foundry.toml
Labels: AuditNotRequired

#981 Update solc and evm version
  .github/workflows/enforceTestCoverage.yml
  bun.lock
  foundry.toml
  package.json
  script/removeDuplicateEventsFromABI.ts
  test/solidity/Facets/CBridgeAndFeeCollection.t.sol
  test/solidity/Facets/CalldataVerificationFacet.t.sol
Labels: WIP, AuditNotRequired

#1113 Integrate CREATE3Factory into contracts repo (and deploy all flow)
  script/deploy/deployAllContracts.sh
  script/deploy/deployAndStoreCREATE3Factory.sh
  script/deploy/facets/DeployCREATE3Factory.s.sol
Labels: AuditNotRequired

#1119 deploy ReceiverStargateV2 & Permit2Proxy to superposition
  config/permit2Proxy.json
  deployments/_deployments_log_file.json
  deployments/superposition.diamond.json
  deployments/superposition.json
Labels: AuditNotRequired

#1123 Redeploy AcrossV3 on POL (and update deploy scripts to use wrappedNative from networks.json)
  deployments/_deployments_log_file.json
  deployments/polygon.diamond.json
  deployments/polygon.json
  script/deploy/facets/DeployAcrossFacet.s.sol
  script/deploy/facets/DeployAcrossFacetPacked.s.sol
  script/deploy/facets/DeployAcrossFacetPackedV3.s.sol
  script/deploy/facets/DeployAcrossFacetV3.s.sol
  script/deploy/resources/deployRequirements.json
  script/deploy/zksync/DeployAcrossFacetPackedV3.zksync.s.sol
  script/deploy/zksync/DeployAcrossFacetV3.zksync.s.sol
Labels: AuditNotRequired

#1114 Implement deploy-safe script
  bun.lock
  package.json
  script/deploy/safe/deploy-safe.ts
Labels: AuditNotRequired

#1075 LF-12878 - Update HopFacet docs/comments
  docs/HopFacet.md
  src/Facets/HopFacet.sol
Labels: AuditNotRequired

#1122 add explicit permissions for git actions (and disable Slither)
  .github/workflows/createPRsAsDraft.yml
  .github/workflows/diamondEmergencyPause.yml
  .github/workflows/enforceTestCoverage.yml
  .github/workflows/ensureSCCoreDevApproval.yml
  .github/workflows/forge.yml
  .github/workflows/healthCheckForNewNetworkDeployment.yml
  .github/workflows/jsonChecker.yml
  .github/workflows/networkSecretsChecker.yml
  .github/workflows/olympixStaticAnalysis.yml
  .github/workflows/protectAuditLabels.yml
  .github/workflows/protectAuditorsGroup.yml
  .github/workflows/protectSecurityRelevantCode.yml
  .github/workflows/securityAlertsReview.yml
  .github/workflows/types.yaml
  .github/workflows/unreviewedPRReminder.yml
  .github/workflows/updateScriptConfigReminder.yml
  .github/workflows/versionControlAndAuditCheck.yml
  .github/workflows_deactivated/slither.yaml
  conventions.md
Labels: AuditNotRequired

#1066 Add unpause diamond script
  config/networks.json
  deployments/zksync.json
  package.json
  script/demoScripts/utils/demoScriptHelpers.ts
  script/deploy/safe/add-safe-owners-and-threshold.ts
  script/deploy/safe/confirm-safe-tx.ts
  script/deploy/safe/propose-to-safe.ts
  script/deploy/safe/safe-utils.ts
  script/tasks/unpauseAllDiamonds.ts
  script/utils/viemScriptHelpers.ts
Labels: AuditNotRequired

#1115 Deploy LiFiDEXAggregator 1.8.0 (VelodromeV2 updated)
  config/dexs.json
  config/gaszip.json
  deployments/_deployments_log_file.json
  deployments/apechain.diamond.json
  deployments/apechain.json
  deployments/base.diamond.json
  deployments/base.json
  deployments/corn.diamond.json
  deployments/corn.json
  deployments/ink.diamond.json
  deployments/ink.json
  deployments/lisk.diamond.json
  deployments/lisk.json
  deployments/mode.diamond.json
  deployments/mode.json
  deployments/optimism.diamond.json
  deployments/optimism.json
  deployments/soneium.diamond.json
  deployments/soneium.json
  deployments/sonic.diamond.json
  deployments/sonic.json
  deployments/superposition.diamond.json
  deployments/superposition.json
  deployments/swellchain.diamond.json
  deployments/swellchain.json
  deployments/unichain.diamond.json
  deployments/unichain.json
  script/deploy/_targetState.json
Labels: AuditNotRequired

#1089 Deploy etherlink
  .env.example
  .github/workflows/diamondEmergencyPause.yml
  config/dexs.json
  config/gaszip.json
  config/global.json
  config/networks.json
  config/permit2Proxy.json
  deployments/_deployments_log_file.json
  deployments/etherlink.diamond.json
  deployments/etherlink.json
  foundry.toml
  script/deploy/_targetState.json
  script/deploy/healthCheck.ts
  script/utils/viemScriptHelpers.ts
Labels: AuditNotRequired
