Repository lifinance/contracts, pull requests merged in 2025-01, with the labels that each got.

#911 Include outputAmountPercent for origin swaps to help improve price [AcrossFacetV3 v1.1.0]
  audit/auditLog.json
  audit/reports/2025.01.06_AcrossFacetV3(v1.1.0).pdf
  deployments/_deployments_log_file.json
  deployments/arbitrum.diamond.staging.json
  deployments/arbitrum.staging.json
  deployments/optimism.diamond.staging.json
  deployments/optimism.staging.json
  docs/AcrossFacetV3.md
  script/demoScripts/demoAcrossV3.ts
  script/demoScripts/utils/demoScriptHelpers.ts
  src/Facets/AcrossFacetV3.sol
  test/solidity/Facets/AcrossFacetPackedV3.t.sol
  test/solidity/Facets/AcrossFacetV3.t.sol
  test/solidity/Facets/CalldataVerificationFacet.t.sol
Labels: AuditCompleted, AuditRequired

#915 Deploy Stargate to Rootstock and Fuse
  config/stargate.json
  deployments/_deployments_log_file.json
  deployments/fuse.diamond.json
  deployments/fuse.json
  deployments/rootstock.diamond.json
  deployments/rootstock.json
  script/deploy/_targetState.json
Labels: AuditNotRequired

#827 Debridge DLN Facet (Version 1.0.0) [DeBridgeDlnFacet v1.0.0]
  archive/scripts/Deploy/UpdateDeBridgeDlnFacet.s.sol
  audit/auditLog.json
  audit/reports/2024.12.05_DeBridgeDlnFacet(v1.0.0).pdf
  config/dln.json
  config/networks.json
  deployments/_deployments_log_file.json
  deployments/arbitrum.staging.json
  deployments/polygon.diamond.staging.json
  deployments/polygon.staging.json
  docs/DeBridgeDlnFacet.md
  docs/README.md
  script/demoScripts/demoDLN.ts
  script/deploy/facets/DeployDeBridgeDlnFacet.s.sol
  script/deploy/facets/UpdateDeBridgeDlnFacet.s.sol
  src/Facets/DeBridgeDlnFacet.sol
  test/solidity/Facets/DeBridgeDlnFacet.t.sol
Labels: AuditCompleted, AuditRequired

#916 Deploy Relay to Prod
  config/relay.json
  deployments/_deployments_log_file.json
  deployments/arbitrum.json
  deployments/avalanche.json
  deployments/base.json
  deployments/blast.json
  deployments/boba.json
  deployments/bsc.json
  deployments/gnosis.json
  deployments/linea.json
  deployments/lisk.json
  deployments/mainnet.json
  deployments/mantle.json
  deployments/mode.json
  deployments/optimism.json
  deployments/polygon.json
  deployments/polygonzkevm.json
  deployments/scroll.json
  deployments/sei.json
  deployments/taiko.json
  deployments/worldchain.json
  deployments/zksync.json
  script/deploy/zksync/DeployRelayFacet.s.sol
Labels: AuditNotRequired

#914 Deploy Across Fix to Prod
  deployments/_deployments_log_file.json
  deployments/arbitrum.diamond.json
  deployments/arbitrum.json
  deployments/base.diamond.json
  deployments/base.json
  deployments/blast.diamond.json
  deployments/blast.json
  deployments/linea.diamond.json
  deployments/linea.json
  deployments/lisk.diamond.json
  deployments/lisk.json
  deployments/mainnet.diamond.json
  deployments/mainnet.json
  deployments/mode.diamond.json
  deployments/mode.json
  deployments/optimism.diamond.json
  deployments/optimism.json
  deployments/polygon.diamond.json
  deployments/polygon.json
  deployments/scroll.diamond.json
  deployments/scroll.json
  deployments/worldchain.json
  deployments/zksync.diamond.json
  deployments/zksync.json
  script/utils/fetch-missing-deployments.ts
Labels: AuditNotRequired

#913 Block old RUNE token on Mainnet [ThorSwapFacet v1.2.1]
  src/Facets/ThorSwapFacet.sol
  test/solidity/Facets/ThorSwapFacet.t.sol
Labels: AuditRequired

#917 Add Audit Report for ThorSwapFacet
  audit/auditLog.json
  audit/reports/2025.01.09_ThorSwapFacet(v1.2.1).pdf
Labels: AuditNotRequired

#912 Use SafeTransferLib for ETH transfers [GasZipFacet v2.0.1,LibAsset v1.0.2,FeeCollector v1.0.1,GasZipPeriphery v1.0.1,LiFiDEXAggregator v1.5.1,LiFuelFeeCollector v1.0.2,Permit2Proxy v1.0.2,Receiver v2.0.3,ReceiverAcrossV3 v1.0.3,ReceiverStargateV2 v1.0.1,RelayerCelerIM v2.0.1,TokenWrapper v1.0.1]
  audit/auditLog.json
  audit/reports/2025.01.09_SafeTransferETHUpdate.pdf
  src/Facets/GasZipFacet.sol
  src/Libraries/LibAsset.sol
  src/Periphery/FeeCollector.sol
  src/Periphery/GasZipPeriphery.sol
  src/Periphery/LiFiDEXAggregator.sol
  src/Periphery/LiFuelFeeCollector.sol
  src/Periphery/Permit2Proxy.sol
  src/Periphery/Receiver.sol
  src/Periphery/ReceiverAcrossV3.sol
  src/Periphery/ReceiverStargateV2.sol
  src/Periphery/RelayerCelerIM.sol
  src/Periphery/TokenWrapper.sol
  test/solidity/Periphery/Permit2Proxy.t.sol
  test/solidity/Periphery/ReceiverAcrossV3.t.sol
  test/solidity/Periphery/ReceiverStargateV2.t.sol
Labels: AuditCompleted, AuditRequired

#909 Integrate WithdrawablePeriphery [ERC20Proxy v1.1.0,Executor v2.1.0,LiFiDEXAggregator v1.6.0,Receiver v2.1.0,ReceiverAcrossV3 v1.1.0,ReceiverStargateV2 v1.1.0,RelayerCelerIM v2.1.1,TokenWrapper v1.1.0]
  audit/auditLog.json
  audit/reports/2025.01.09_WithdrawablePeripheryUpdates.pdf
  docs/Receiver.md
  docs/ReceiverAcrossV3.md
  docs/ReceiverStargateV2.md
  script/deploy/facets/DeployTokenWrapper.s.sol
  script/deploy/zksync/DeployTokenWrapper.s.sol
  src/Periphery/ERC20Proxy.sol
  src/Periphery/Executor.sol
  src/Periphery/LiFiDEXAggregator.sol
  src/Periphery/Receiver.sol
  src/Periphery/ReceiverAcrossV3.sol
  src/Periphery/ReceiverStargateV2.sol
  src/Periphery/RelayerCelerIM.sol
  src/Periphery/TokenWrapper.sol
  test/solidity/Facets/CelerIMFacet.t.sol
  test/solidity/Periphery/Executor.t.sol
  test/solidity/Periphery/Receiver.t.sol
  test/solidity/Periphery/ReceiverAcrossV3.t.sol
  test/solidity/Periphery/ReceiverStargateV2.t.sol
  test/solidity/Periphery/RelayerCelerIM.t.sol
  test/solidity/Periphery/TokenWrapper.t.sol
Labels: AuditCompleted, AuditRequired

#910 Audit fixes [GasZipFacet v2.0.2]
  audit/auditLog.json
  audit/reports/report-cantinacode-lifi-1216.pdf
  src/Facets/GasZipFacet.sol
  src/Periphery/Permit2Proxy.sol
Labels: AuditCompleted, AuditRequired

#907 Adds ERC20Proxy checks to healthcheck script
  deployments/_deployments_log_file.json
  deployments/zksync.json
  script/deploy/healthCheck.ts
  script/tasks/updateERC20Proxy.sh
Labels: AuditNotRequired

#903 add initial version of LiFiTimelockController [LiFiTimelockController v1.0.0]
  audit/auditLog.json
  audit/reports/2025.01.10_Timelock(v1.0.0).pdf
  src/Security/LiFiTimelockController.sol
  test/solidity/Security/LiFiTimelockController.t.sol
Labels: AuditCompleted, AuditRequired

#870 removes duplicate version tag in DiamondCutFacet
  src/Facets/DiamondCutFacet.sol
Labels: AuditRequired

#767 (fix): adds calldata extraction handling for GenericSwapV3 single swap calls (CallDataVerificationFacet v1.2.0) [CalldataVerificationFacet v1.2.0,IAcrossSpokePool v1.0.0]
  audit/auditLog.json
  audit/reports/2024.09.02_CalldataVerificationFacet.pdf
  src/Facets/CalldataVerificationFacet.sol
  src/Interfaces/IAcrossSpokePool.sol
  test/solidity/Facets/CalldataVerificationFacet.t.sol
Labels: AuditCompleted, AuditRequired

#919 ci(actions): remove forceMerge workflow
  .github/workflows/forceMergePRBypassAudit.yml
Labels: AuditNotRequired

#926 updated foundry.toml with etherscanV2 links
  deployments/base.json
  foundry.toml
Labels: AuditNotRequired

#929 Redeploy relay facet
  deployments/_deployments_log_file.json
Labels: AuditNotRequired

#927 use etherscanv2 for avalanche and mainnet
  foundry.toml
Labels: AuditNotRequired

#934 rename cantina audit file and adjust auditLog
  audit/auditLog.json
  audit/reports/2024.12.02_RelayFacet(v1.0.0).pdf
  audit/reports/2025.01.10_Cantina_PreComp.pdf
Labels: AuditNotRequired

#932 Deploy DeBridgeDLNFacet to production
  .gitignore
  deployments/_deployments_log_file.json
  deployments/arbitrum.json
  deployments/avalanche.json
  deployments/base.json
  deployments/bsc.json
  deployments/gnosis.json
  deployments/linea.json
  deployments/mainnet.json
  deployments/metis.json
  deployments/optimism.json
  deployments/polygon.json
Labels: AuditNotRequired

#918 Deploy to Sonic
  .github/workflows/diamondEmergencyPause.yml
  config/amarok.json
  config/dexs.json
  config/gaszip.json
  config/global.json
  config/networks.json
  config/stargate.json
  config/tokenwrapper.json
  deployments/_deployments_log_file.json
  deployments/sonic.diamond.json
  deployments/sonic.json
  foundry.toml
  networks
  script/deploy/_targetState.json
Labels: AuditNotRequired

#935 Remove duplicate SAFE information and hardhat from codebase
  .eslintrc.cjs
  .github/workflows/enforceTestCoverage.yml
  .prettierrc.cjs
  config/arbitrum.json
  config/debridge.json
  config/global.json
  config/gnosis.json
  config/hyphen.json
  config/omni.json
  config/polygon.json
  config/wormhole.json
  hardhat.config.ts
  package.json
  remappings.txt
  script/deploy/deployUpgradesToSAFE.sh
  script/deploy/facets/DeployGenericSwapFacetV3.s.sol
  script/deploy/facets/DeployTokenWrapper.s.sol
  script/deploy/healthCheck.ts
  script/deploy/safe/add-owners-to-safe.ts
  script/deploy/safe/config.ts
  script/deploy/safe/propose-to-safe.ts
  script/deploy/zksync/022_deploy_emergency_pause_facet.ts
  script/deploy/zksync/DeployGenericSwapFacetV3.s.sol
  script/deploy/zksync/DeployTokenWrapper.s.sol
  script/tasks/diamondEMERGENCYPause.sh
  script/tasks/diamondSyncSigs.sh
  script/tasks/diamondUpdateFacet.sh
  script/tasks/diamondUpdatePeriphery.sh
  script/tasks/fundNewWalletOnAllChains.ts
  script/utils/diamond.ts
  script/utils/filter_lcov.ts
  slither.config.json
  tasks/generateDiamondABI.ts
  tsconfig.json
  yarn.lock
Labels: AuditNotRequired

#943 Deprecate immutable lf 11830
  archive/scripts/Tasks/MakeLiFiDiamondImmutable.s.sol
  archive/scripts/Tasks/RemoveUnusableSelectorsFromImmutableDiamond.s.sol
  archive/scripts/removeUnusableFunctionsForImmutable.sh
  deployments/arbitrum.diamond.immutable.json
  deployments/aurora.diamond.immutable.json
  deployments/avalanche.diamond.immutable.json
  deployments/base.diamond.immutable.json
  deployments/boba.diamond.immutable.json
  deployments/bsc.diamond.immutable.json
  deployments/celo.diamond.immutable.json
  deployments/cronos.diamond.immutable.json
  deployments/evmos.diamond.immutable.json
  deployments/fantom.diamond.immutable.json
  deployments/fuse.diamond.immutable.json
  deployments/gnosis.diamond.immutable.json
  deployments/goerli.diamond.immutable.json
  deployments/goerli.diamond.immutable.staging.json
  deployments/linea.diamond.immutable.json
  deployments/lineatest.diamond.immutable.json
  deployments/mainnet.diamond.immutable.json
  deployments/moonbeam.diamond.immutable.json
  deployments/moonriver.diamond.immutable.json
  deployments/mumbai.diamond.immutable.json
  deployments/mumbai.diamond.immutable.staging.json
  deployments/okx.diamond.immutable.json
  deployments/optimism.diamond.immutable.json
  deployments/polygon.diamond.immutable.json
  deployments/polygon.diamond.immutable.staging.json
  deployments/polygonzkevm.diamond.immutable.json
  deployments/testNetwork.diamond.json
  deployments/testNetwork.json
  deployments/velas.diamond.immutable.json
Labels: AuditNotRequired

#941 fix erroneous flags in deployRequirements
  script/deploy/resources/deployRequirements.json
Labels: AuditNotRequired

#931 add isContract check when reading contract addresses from config files
  config/across.json
  deployments/optimism.json
  script/deploy/facets/DeployAcrossFacet.s.sol
  script/deploy/facets/DeployAcrossFacetPacked.s.sol
  script/deploy/facets/DeployAcrossFacetPackedV3.s.sol
  script/deploy/facets/DeployAcrossFacetV3.s.sol
  script/deploy/facets/DeployAllBridgeFacet.s.sol
  script/deploy/facets/DeployAmarokFacet.s.sol
  script/deploy/facets/DeployAmarokFacetPacked.s.sol
  script/deploy/facets/DeployArbitrumBridgeFacet.s.sol
  script/deploy/facets/DeployCBridgeFacet.s.sol
  script/deploy/facets/DeployCBridgeFacetPacked.s.sol
  script/deploy/facets/DeployCelerCircleBridgeFacet.s.sol
  script/deploy/facets/DeployCelerIMFacet.s.sol
  script/deploy/facets/DeployDeBridgeDlnFacet.s.sol
  script/deploy/facets/DeployExecutor.s.sol
  script/deploy/facets/DeployGasZipFacet.s.sol
  script/deploy/facets/DeployGasZipPeriphery.s.sol
  script/deploy/facets/DeployGenericSwapFacetV3.s.sol
  script/deploy/facets/DeployGnosisBridgeFacet.s.sol
  script/deploy/facets/DeployLiFiDiamond.s.sol
  script/deploy/facets/DeployMayanFacet.s.sol
  script/deploy/facets/DeployOmniBridgeFacet.s.sol
  script/deploy/facets/DeployPermit2Proxy.s.sol
  script/deploy/facets/DeployPolygonBridgeFacet.s.sol
  script/deploy/facets/DeployReceiver.s.sol
  script/deploy/facets/DeployReceiverAcrossV3.s.sol
  script/deploy/facets/DeployReceiverStargateV2.s.sol
  script/deploy/facets/DeployRelayFacet.s.sol
  script/deploy/facets/DeployRelayerCelerIM.s.sol
  script/deploy/facets/DeploySquidFacet.s.sol
  script/deploy/facets/DeployStargateFacet.s.sol
  script/deploy/facets/DeployStargateFacetV2.s.sol
  script/deploy/facets/DeploySymbiosisFacet.s.sol
  script/deploy/facets/DeployThorSwapFacet.s.sol
  script/deploy/facets/DeployTokenWrapper.s.sol
  script/deploy/facets/UpdateCoreFacets.s.sol
  script/deploy/facets/UpdateOptimismBridgeFacet.s.sol
  script/deploy/facets/utils/ScriptBase.sol
  script/deploy/zksync/DeployAcrossFacetPackedV3.s.sol
  script/deploy/zksync/DeployAcrossFacetV3.s.sol
  script/deploy/zksync/DeployExecutor.s.sol
  script/deploy/zksync/DeployGasZipFacet.s.sol
  script/deploy/zksync/DeployGasZipPeriphery.s.sol
  script/deploy/zksync/DeployGenericSwapFacetV3.s.sol
  script/deploy/zksync/DeployLiFiDiamond.s.sol
  script/deploy/zksync/DeployPermit2Proxy.s.sol
  script/deploy/zksync/DeployReceiver.s.sol
  script/deploy/zksync/DeployReceiverAcrossV3.s.sol
  script/deploy/zksync/DeployRelayFacet.s.sol
  script/deploy/zksync/DeployTokenWrapper.s.sol
  script/deploy/zksync/utils/DeployScriptBase.sol
  script/deploy/zksync/utils/ScriptBase.sol
  script/tasks/solidity/AddTokenApprovalsToCBridgeFacetPacked.s.sol
  script/tasks/solidity/CheckExecutorAndReceiver.s.sol
  templates/facetDeployScript.template.hbs
Labels: AuditNotRequired

#946 Small codebase fixes
  config/networks.json
  src/Facets/DeBridgeDlnFacet.sol
Labels: AuditCompleted, AuditRequired

#948 Small codebase fixes
  config/networks.json
Labels: AuditNotRequired

#940 update git action dependency
  .github/workflows/forge.yml
Labels: AuditNotRequired

#936 Introduces a git action that checks selected (important) JSON files for semantic issues
  .github/workflows/jsonChecker.yml
  deployments/polygon.diamond.staging.json
Labels: AuditNotRequired

#954 Added ETH_NODE_URI_BASE and ordered in alphabetic way
  .github/workflows/enforceTestCoverage.yml
  .github/workflows/forge.yml
Labels: AuditNotRequired

#958 tests fixed that were failing in latest foundry nightly version
  test/solidity/Libraries/LibUtil.t.sol
Labels: AuditNotRequired

#960 Fix safe scripts and add pre-selected action when running with SAFE_SIGNER_PRIVATE_KEY (=can only sign)
  package.json
  script/deploy/safe/add-owners-to-safe.ts
  script/deploy/safe/confirm-safe-tx.ts
  tsconfig.json
Labels: AuditNotRequired

#952 fixed contract verification on Gravity
  config/networks.json
  deployments/gravity.json
  foundry.toml
Labels: AuditNotRequired

#957 remove unused testnet entries from foundry.toml
  foundry.toml
Labels: AuditNotRequired

#962 add config flag to disable precompilation for scriptMaster
  script/config.example.sh
  script/scriptMaster.sh
Labels: AuditNotRequired

#955 Added preinstall script
  package.json
  preinstall.sh
Labels: AuditNotRequired

#942 Update zksync deploy script naming
  script/deploy/deploySingleContract.sh
  script/deploy/zksync/DeployAcrossFacetPackedV3.zksync.s.sol
  script/deploy/zksync/DeployAcrossFacetV3.zksync.s.sol
  script/deploy/zksync/DeployCalldataVerificationFacet.zksync.s.sol
  script/deploy/zksync/DeployDexManagerFacet.zksync.s.sol
  script/deploy/zksync/DeployDiamondCutFacet.zksync.s.sol
  script/deploy/zksync/DeployDiamondLoupeFacet.zksync.s.sol
  script/deploy/zksync/DeployERC20Proxy.zksync.s.sol
  script/deploy/zksync/DeployEmergencyPauseFacet.zksync.s.sol
  script/deploy/zksync/DeployExecutor.zksync.s.sol
  script/deploy/zksync/DeployFeeCollector.zksync.s.sol
  script/deploy/zksync/DeployGasZipFacet.zksync.s.sol
  script/deploy/zksync/DeployGasZipPeriphery.zksync.s.sol
  script/deploy/zksync/DeployGenericSwapFacet.zksync.s.sol
  script/deploy/zksync/DeployGenericSwapFacetV3.zksync.s.sol
  script/deploy/zksync/DeployLiFiDEXAggregator.zksync.s.sol
  script/deploy/zksync/DeployLiFiDiamond.zksync.s.sol
  script/deploy/zksync/DeployOwnershipFacet.zksync.s.sol
  script/deploy/zksync/DeployPeripheryRegistryFacet.zksync.s.sol
  script/deploy/zksync/DeployPermit2Proxy.zksync.s.sol
  script/deploy/zksync/DeployReceiver.zksync.s.sol
  script/deploy/zksync/DeployReceiverAcrossV3.zksync.s.sol
  script/deploy/zksync/DeployRelayFacet.zksync.s.sol
  script/deploy/zksync/DeployStandardizedCallFacet.zksync.s.sol
  script/deploy/zksync/DeployTokenWrapper.zksync.s.sol
  script/deploy/zksync/DeployWithdrawFacet.zksync.s.sol
  script/scriptMaster.sh
Labels: AuditNotRequired

#956 missing audit reports added for LiFiDEXAggregator
  audit/auditLog.json
  audit/reports/2024.02.01_LiFiDEXAggregator(v1.0.0).pdf
  audit/reports/2025.01.17_LiFiDexAggregator(v1.1.0).pdf
  audit/reports/2025.01.17_LiFiDexAggregator(v1.2.0).pdf
  audit/reports/2025.01.17_LiFiDexAggregator(v1.3.0).pdf
  audit/reports/2025.01.17_LiFiDexAggregator(v1.4.0).pdf
Labels: AuditNotRequired
