Repository lifinance/contracts, pull requests merged in 2025-02, with the labels that each got.

#966 actions updated to use stable version instead of nightly
  .github/workflows/enforceTestCoverage.yml
  .github/workflows/forge.yml
  .github/workflows_deactivated/enforceTestCoverage.yml
Labels: AuditNotRequired

#967 add pagination flag to always get the latest reviews of a PR
  .github/workflows/ensureSCCoreDevApproval.yml
Labels: AuditNotRequired

#969 config: add new okx signature
  config/sigs.json
Labels: AuditNotRequired

#965 foundry flags updated
  script/deploy/deploySingleContract.sh
  script/deploy/deployUpgradesToSAFE.sh
  script/tasks/acceptOwnershipTransferPeriphery.sh
  script/tasks/checkExecutorAndReceiver.sh
  script/tasks/diamondUpdateFacet.sh
  script/tasks/diamondUpdateSgConfig.sh
  script/tasks/updateFacetConfig.sh
Labels: AuditNotRequired

#961 deploy relay facet to gravity chain
  deployments/_deployments_log_file.json
  deployments/gravity.diamond.json
  deployments/gravity.json
  script/deploy/safe/propose-to-safe.ts
  script/scriptMaster.sh
  script/tasks/diamondUpdateFacet.sh
Labels: AuditNotRequired

#977 pull only the latest 100 items from git API
  .github/workflows/protectSecurityRelevantCode.yml
Labels: AuditNotRequired

#924 Deploy contracts to Abstract
  .env.example
  .github/workflows/diamondEmergencyPause.yml
  config/amarok.json
  config/dexs.json
  config/gaszip.json
  config/networks.json
  config/relay.json
  config/stargate.json
  config/tokenwrapper.json
  deployments/_deployments_log_file.json
  deployments/abstract.diamond.json
  deployments/abstract.json
  foundry.toml
  networks
  package.json
  script/deploy/_targetState.json
  script/deploy/deploySingleContract.sh
  script/deploy/healthCheck.ts
  script/deploy/safe/config.ts
  script/deploy/zksync/DeployAccessManagerFacet.s.sol
  script/deploy/zksync/DeployCalldataVerificationFacet.zksync.s.sol
  script/deploy/zksync/DeployExecutor.zksync.s.sol
  script/deploy/zksync/DeployLiFiDEXAggregator.zksync.s.sol
  script/deploy/zksync/DeployReceiverStargateV2.s.sol
  script/deploy/zksync/DeployStandardizedCallFacet.zksync.s.sol
  script/deploy/zksync/DeployStargateFacetV2.s.sol
  script/helperFunctions.sh
  yarn.lock
Labels: AuditCompleted, AuditNotRequired

#968 fixes contract verification for EtherscanV2 and removes missing .env …
  script/helperFunctions.sh
Labels: AuditNotRequired

#921 Fix and improve audit verifier action
  .github/workflows/ensureSCCoreDevApproval.yml
  .github/workflows/protectAuditLabels.yml
  .github/workflows/protectSecurityRelevantCode.yml
  .github/workflows/versionControlAndAuditCheck.yml
  .github/workflows_deactivated/ensureDeployProcessIntegrity.yml
  .github/workflows_deactivated/ensureSCCoreDevApproval.yml
  .github/workflows_deactivated/protectAuditCompletedLabel.yml
  .github/workflows_deactivated/protectAuditFolder.yml
  .github/workflows_deactivated/verifyAudit.yml
  .github/workflows_deactivated/versionCheck.yml
Labels: AuditNotRequired

#923 Deploy Across Fix to Worldchain
  deployments/worldchain.diamond.json
  deployments/worldchain.json
Labels: AuditNotRequired

#972 Update git actions to send messages to Slack instead of Discord
  .github/workflows/diamondEmergencyPause.yml
  .github/workflows/networkSecretsChecker.yml
  .github/workflows/unreviewedPRReminder.yml
  .github/workflows/updateScriptConfigReminder.yml
Labels: AuditNotRequired

#933 Redeploy Relay to Mode and Scroll
  deployments/_deployments_log_file.json
  deployments/mode.diamond.json
  deployments/mode.json
  deployments/scroll.diamond.json
  deployments/scroll.json
Labels: AuditNotRequired

#976 fixed preinstall script
  preinstall.sh
Labels: AuditNotRequired

#980 LF-11929 - Moved core facets to global.json and made adjustments
  config/global.json
  script/config.example.sh
  script/deploy/deployAllContracts.sh
  script/deploy/deployCoreFacets.sh
  script/deploy/healthCheck.ts
  script/helperFunctions.sh
Labels: AuditNotRequired

#988 flag added to allow zeroAddress in helper function
  script/deploy/facets/DeployArbitrumBridgeFacet.s.sol
  script/deploy/facets/DeployCelerCircleBridgeFacet.s.sol
  script/deploy/facets/DeployGenericSwapFacetV3.s.sol
  script/deploy/facets/DeployReceiver.s.sol
  script/deploy/facets/DeployRelayFacet.s.sol
  script/deploy/facets/utils/ScriptBase.sol
  script/deploy/zksync/DeployGenericSwapFacetV3.zksync.s.sol
  script/deploy/zksync/DeployReceiver.zksync.s.sol
  script/deploy/zksync/DeployRelayFacet.zksync.s.sol
  templates/facetDeployScript.template.hbs
Labels: AuditNotRequired

#990 Added gum to preinstall script
  preinstall.sh
Labels: AuditNotRequired

#978 Deploy berachain
  .env.example
  .github/workflows/diamondEmergencyPause.yml
  archive/test/LiFiDiamondImmutable.t.sol
  config/amarok.json
  config/dexs.json
  config/gaszip.json
  config/global.json
  config/networks.json
  config/permit2Proxy.json
  config/relay.json
  config/stargate.json
  config/symbiosis.json
  config/tokenwrapper.json
  deployments/_deployments_log_file.json
  deployments/berachain.diamond.json
  deployments/berachain.json
  foundry.toml
  networks
  package.json
  script/deploy/_targetState.json
  script/deploy/facets/UpdateCoreFacets.s.sol
  script/deploy/healthCheck.ts
  script/helperFunctions.sh
  test/solidity/Facets/GasZipFacet.t.sol
  test/solidity/Facets/RelayFacet.t.sol
  test/solidity/Helpers/WithdrawablePeriphery.t.sol
  test/solidity/Periphery/GasZipPeriphery.t.sol
  test/solidity/Periphery/Permit2Proxy.t.sol
  yarn.lock
Labels: AuditNotRequired

#982 symbiosis facet deployed to gnosis
  config/symbiosis.json
  deployments/_deployments_log_file.json
  deployments/gnosis.diamond.json
  deployments/gnosis.json
Labels: AuditNotRequired

#983 Add deploy calldata logging lf 12257
  script/deploy/facets/utils/DeployScriptBase.sol
  script/deploy/facets/utils/UpdateScriptBase.sol
  script/tasks/diamondUpdateFacet.sh
Labels: AuditNotRequired

#992 Deploy all contracts to unichain
  .env.example
  .github/workflows/diamondEmergencyPause.yml
  config/across.json
  config/amarok.json
  config/dexs.json
  config/global.json
  config/networks.json
  config/permit2Proxy.json
  config/relay.json
  config/stargate.json
  config/tokenwrapper.json
  deployments/_deployments_log_file.json
  deployments/berachain.diamond.json
  deployments/berachain.json
  deployments/unichain.diamond.json
  deployments/unichain.json
  foundry.toml
  networks
  script/deploy/_targetState.json
  script/deploy/deployPeripheryContracts.sh
  script/deploy/facets/UpdateCoreFacets.s.sol
  script/deploy/healthCheck.ts
  script/helperFunctions.sh
Labels: AuditNotRequired

#1000 replace testFail_ with testRevert_ pattern due to deprecation
  script/deploy/facets/utils/DeployScriptBase.sol
  test/solidity/Facets/AcrossFacet.t.sol
  test/solidity/Facets/AcrossFacetV3.t.sol
  test/solidity/Facets/CBridgeRefund.t.sol
  test/solidity/Facets/DexManagerFacet.t.sol
  test/solidity/Facets/OwnershipFacet.t.sol
  test/solidity/Facets/RelayFacet.t.sol
  test/solidity/Helpers/TransferrableOwnership.t.sol
  test/solidity/Periphery/Executor.t.sol
  test/solidity/Periphery/FeeCollector.t.sol
Labels: AuditNotRequired

#997 feat: enable kyberswap openocean berachain
  config/dexs.json
Labels: AuditNotRequired

#993 deployed stargate to gnosis
  config/stargate.json
  deployments/_deployments_log_file.json
  deployments/gnosis.diamond.json
  deployments/gnosis.json
  script/deploy/_targetState.json
Labels: AuditNotRequired

#994 Deploy all contracts to soneium
  .env.example
  .github/workflows/diamondEmergencyPause.yml
  config/across.json
  config/amarok.json
  config/dexs.json
  config/gaszip.json
  config/global.json
  config/networks.json
  config/permit2Proxy.json
  config/relay.json
  config/stargate.json
  config/tokenwrapper.json
  deployments/_deployments_log_file.json
  deployments/soneium.diamond.json
  deployments/soneium.json
  foundry.toml
  networks
  script/config.example.sh
  script/deploy/_targetState.json
  script/deploy/deployAllContracts.sh
  script/deploy/healthCheck.ts
  script/deploy/resources/contractSpecificReminders.sh
  script/tasks/diamondUpdateFacet.sh
  script/tasks/diamondUpdatePeriphery.sh
  script/tasks/updateERC20Proxy.sh
Labels: AuditNotRequired

#1004 feat: whitelist lda sonic
  config/dexs.json
Labels: AuditNotRequired

#991 LF-12212 Adapt git action (ensure test coverage) to run only when needed
  .github/workflows/enforceTestCoverage.yml
Labels: AuditNotRequired

#975 Added tests
  test/solidity/Facets/AccessManagerFacet.t.sol
  test/solidity/Facets/AcrossFacetPacked.t.sol
  test/solidity/Facets/AmarokFacetPacked.t.sol
  test/solidity/Facets/CBridge.t.sol
  test/solidity/Facets/CBridgeFacetPacked.t.sol
  test/solidity/Facets/DeBridgeDlnFacet.t.sol
  test/solidity/Facets/DexManagerFacet.t.sol
  test/solidity/utils/MockFailingContract.sol
Labels: AuditNotRequired

#1005 feat(sushi): add RouteProcessorV6 addresses and functions
  config/dexs.json
  config/sigs.json
Labels: AuditNotRequired

#1001 Added Olympix static analysis with alerts review
  .github/workflows/olympixStaticAnalysis.yml
  .github/workflows/securityAlertsReview.yml
Labels: AuditNotRequired

#1006 Remove non contract DEXs
  config/dexs.json
Labels: AuditNotRequired

#1010 Fix - added paths for security alerts review
  .github/workflows/securityAlertsReview.yml
Labels: AuditNotRequired

#1012 feat(sushi): add RouteProcessorV6 addresses for moonriver&moonbeam
  config/dexs.json
Labels: AuditNotRequired

#1013 feat(dexs): enable paraswap on gnosis
  config/dexs.json
Labels: AuditNotRequired

#1017 Deploy thorswap fix to mainnet
  deployments/_deployments_log_file.json
  deployments/mainnet.diamond.json
  deployments/mainnet.json
Labels: AuditNotRequired

#1009 fix audit-verifier action ( comma- vs. newline separated formatting of protected contracts)
  .github/workflows/versionControlAndAuditCheck.yml
Labels: AuditNotRequired

#1019 Fixes - warning, changed github token to GIT_ACTIONS_BOT_PAT_CLASSIC
  .github/workflows/olympixStaticAnalysis.yml
  .github/workflows/securityAlertsReview.yml
Labels: AuditNotRequired

#1023 symbiosis facet deployed to unichain
  bun.lock
  config/symbiosis.json
  deployments/_deployments_log_file.json
  deployments/unichain.diamond.json
  deployments/unichain.json
  script/deploy/_targetState.json
Labels: AuditNotRequired

#1026 feat: add redeployed sushiswap routeprocessor V6 contracts on all chains
  config/dexs.json
Labels: AuditNotRequired

#1016 Deploy all contracts to ink
  .env.example
  .github/workflows/diamondEmergencyPause.yml
  config/across.json
  config/dexs.json
  config/gaszip.json
  config/global.json
  config/networks.json
  config/permit2Proxy.json
  config/relay.json
  config/stargate.json
  config/tokenwrapper.json
  deployments/_deployments_log_file.json
  deployments/ink.diamond.json
  deployments/ink.json
  foundry.toml
  networks
  script/deploy/healthCheck.ts
  script/tasks/diamondUpdateFacet.sh
Labels: AuditNotRequired

#999 deprecate LiFuelFacet and standardizedCallFacet
  archive/docs/LIFuelFacet.md
  archive/docs/StandardizedCallFacet.md
  archive/scripts/Deploy/DeployLIFuelFacet.s.sol
  archive/scripts/Deploy/DeployStandardizedCallFacet.s.sol
  archive/scripts/Deploy/UpdateLIFuelFacet.s.sol
  archive/scripts/Deploy/UpdateStandardizedCallFacet.s.sol
  archive/scripts/zkSync/DeployStandardizedCallFacet.zksync.s.sol
  archive/src/Facets/LIFuelFacet.sol
  archive/src/Facets/StandardizedCallFacet.sol
  archive/test/LIFuelFacet.t.sol
  archive/test/StandardizedCallFacet.t.sol
Labels: AuditNotRequired

#1002 Deprecate stargate v1 and amarok
  archive/config/amarok.json
  archive/config/circle.json
  archive/config/hyphen.json
  archive/config/maker.json
  archive/config/multichain.json
  archive/config/stargateV1.json
  archive/config/synapse.json
  archive/config/wormhole.json
  archive/docs/AmarokFacet.md
  archive/docs/Receiver.md
  archive/docs/StargateFacet.md
  archive/scripts/Deploy/DeployAmarokFacet.s.sol
  archive/scripts/Deploy/DeployAmarokFacetPacked.s.sol
  archive/scripts/Deploy/DeployReceiver.s.sol
  archive/scripts/Deploy/DeployStargateFacet.s.sol
  archive/scripts/Deploy/UpdateAmarokFacet.s.sol
  archive/scripts/Deploy/UpdateAmarokFacetPacked.s.sol
  archive/scripts/Deploy/UpdateStargateFacet.s.sol
  archive/scripts/Tasks/AddChainIdsForStargateToDiamond.s.sol
  archive/scripts/Tasks/AddTokenApprovalsToAmarokFacetPacked.s.sol
  archive/scripts/demoScripts/demoAmarokBridge.ts
  archive/scripts/demoScripts/demoDeBridge.ts
  archive/scripts/demoScripts/demoMultichainTx.ts
  archive/scripts/demoScripts/demoSynapseBridge.ts
  archive/scripts/zkSync/DeployReceiver.zksync.s.sol
  archive/src/Facets/AmarokFacetPacked.sol
  archive/src/Facets/StargateFacet.sol
  archive/src/Periphery/Receiver.sol
  archive/test/AmarokFacet.t.sol
  archive/test/AmarokFacetPacked.t.sol
  archive/test/Receiver.t.sol
  archive/test/StargateFacet.t.sol
  config/stargate.json
Labels: waitForAudit, AuditNotRequired

#1031 feat add redeployed sushiswap routeprocessor V6 on zksync
  config/dexs.json
Labels: AuditNotRequired

#1030 Deprecated networks file
  archive/scripts/Tasks/diamondMakeImmutable.sh
  archive/scripts/removeUnusableFunctionsForImmutable.sh
  script/config.example.sh
  script/deploy/deployFacetAndAddToDiamond.sh
  script/helperFunctions.sh
  script/scriptMaster.sh
  script/tasks/acceptOwnershipTransferPeriphery.sh
  script/tasks/checkExecutorAndReceiver.sh
  script/tasks/diamondEMERGENCYPause.sh
  script/tasks/diamondSyncDEXs.sh
  script/tasks/diamondSyncSigs.sh
  script/tasks/diamondUpdatePeriphery.sh
  script/tasks/diamondUpdateSgConfig.sh
  script/tasks/updateFacetConfig.sh
  script/utils/diamondEMERGENCYPauseGitHub.sh
  script/utils/network.ts
Labels: AuditNotRequired

#1029 Deploy relay and stargate to sonic
  config/relay.json
  config/stargate.json
  deployments/_deployments_log_file.json
  deployments/sonic.diamond.json
  deployments/sonic.json
  script/deploy/_targetState.json
  script/deploy/safe/propose-to-safe.ts
Labels: AuditNotRequired

#1028 add GasZipPeriphery address to dexs.json for sonic
  config/dexs.json
Labels: AuditNotRequired
