Repository lifinance/contracts, pull requests merged in 2025-06, with the labels that each got.

#1165 Updated GnosisBridgeFacet [GnosisBridgeFacet v2.0.0,IGnosisBridgeRouter v1.0.0]
  audit/auditLog.json
  audit/reports/2025.06.03_GnosisBridgeFacet(v2.0.0).pdf
  src/Facets/GnosisBridgeFacet.sol
  src/Interfaces/IGnosisBridgeRouter.sol
  src/Periphery/GasZipPeriphery.sol
  test/solidity/Facets/GnosisBridgeFacet.t.sol
  test/solidity/Periphery/GasZipPeriphery.t.sol
Labels: AuditCompleted, AuditRequired

#1181 Updated gasZipChainId for bsc and fixed explorerUrls
  config/networks.json
Labels: AuditNotRequired

#1171 Deploy network Nibiru
  config/dexs.json
  config/gaszip.json
  config/networks.json
  config/permit2Proxy.json
  config/stargateV2.json
  deployments/_deployments_log_file.json
  deployments/nibiru.diamond.json
  deployments/nibiru.json
  foundry.toml
  script/deploy/_targetState.json
  script/deploy/deployAllContracts.sh
  script/deploy/deployAndStoreCREATE3Factory.sh
  script/deploy/deploySingleContract.sh
  script/deploy/safe/deploy-safe.ts
  script/tasks/diamondSyncDEXs.sh
  script/tasks/diamondSyncSigs.sh
Labels: AuditNotRequired, NewNetwork

#1177 redeployed glacis to optimism
  config/glacis.json
  deployments/_deployments_log_file.json
  deployments/optimism.diamond.json
  deployments/optimism.json
Labels: AuditNotRequired

#1175 deployed glacis to corn
  config/glacis.json
  deployments/_deployments_log_file.json
  deployments/corn.diamond.json
  deployments/corn.json
Labels: AuditNotRequired

#1201 feat: add enso contracts to dexs.json
  config/dexs.json
Labels: AuditNotRequired

#1203 config: add openocean address on Flare
  config/dexs.json
Labels: AuditNotRequired

#1199 GenericSwapFacetV3 deployed to mainnet (for Paxos USDL)
  deployments/_deployments_log_file.json
  deployments/mainnet.diamond.json
  deployments/mainnet.json
Labels: AuditNotRequired

#1208 silence some compiler warnings
  script/deploy/facets/DeployCREATE3Factory.s.sol
  test/solidity/Facets/EmergencyPauseFacet.local.t.sol
  test/solidity/Periphery/LiFiDEXAggregator.t.sol
  test/solidity/Periphery/Permit2Proxy.t.sol
  test/solidity/utils/TestAMM.sol
Labels: AuditNotRequired

#1206 deployed glacis to etherlink/flare
  config/glacis.json
  deployments/_deployments_log_file.json
  deployments/etherlink.diamond.json
  deployments/etherlink.json
  deployments/flare.diamond.json
  deployments/flare.json
Labels: AuditNotRequired

#1209 redeployed stargate to unichain
  deployments/_deployments_log_file.json
  deployments/unichain.diamond.json
  deployments/unichain.json
Labels: AuditNotRequired

#1210 redeployed gnosis with correct router address to mainnet
  config/gnosis.json
  deployments/_deployments_log_file.json
  deployments/mainnet.diamond.json
  deployments/mainnet.json
  script/deploy/facets/DeployGnosisBridgeFacet.s.sol
  script/deploy/resources/deployRequirements.json
Labels: AuditNotRequired

#1216 redeployed permit2Proxy
  deployments/_deployments_log_file.json
  deployments/optimism.diamond.staging.json
  deployments/optimism.staging.json
  script/tasks/diamondUpdatePeriphery.sh
Labels: AuditNotRequired

#1215 exclude common values: (false, true, none, verifyContract) and safe/.../out directories from pre-commit check
  .husky/pre-commit
Labels: AuditNotRequired

#1223 Deploy glacis to viction
  config/glacis.json
  deployments/_deployments_log_file.json
  deployments/viction.diamond.json
  deployments/viction.json
  script/deploy/_targetState.json
Labels: AuditNotRequired

#1227 Add a refund address to pioneer facet [PioneerFacet v1.1.0]
  docs/PioneerFacet.md
  script/demoScripts/demoPioneer.ts
  src/Facets/PioneerFacet.sol
  test/solidity/Facets/PioneerFacet.t.sol
Labels: AuditRequired

#1211 Deploy network katana
  config/dexs.json
  config/gaszip.json
  config/networks.json
  config/permit2Proxy.json
  deployments/_deployments_log_file.json
  deployments/katana.diamond.json
  deployments/katana.json
  foundry.toml
  package.json
  script/config.example.sh
  script/deploy/_targetState.json
  script/deploy/deployAllContracts.sh
  script/deploy/detect-evm-version.ts
  script/deploy/healthCheck.ts
  script/deploy/safe/safe-utils.ts
  script/scriptMaster.sh
Labels: AuditNotRequired

#1233 Deploy network vana
  config/dexs.json
  config/gaszip.json
  config/networks.json
  config/permit2Proxy.json
  config/stargateV2.json
  deployments/_deployments_log_file.json
  deployments/vana.diamond.json
  deployments/vana.json
  foundry.toml
  script/deploy/_targetState.json
  script/deploy/deployAllContracts.sh
  script/deploy/deploySingleContract.sh
  script/helperFunctions.sh
Labels: AuditNotRequired

#1236 feat: whitelist openocean and bebop router address on hyperevm
  config/dexs.json
Labels: AuditNotRequired

#1241 add gas estimate multiplier flag for deployments
  config/networks.json
  script/deploy/deploySingleContract.sh
Labels: AuditNotRequired

#1242 config: add sushiswap address on Katana
  config/dexs.json
Labels: AuditNotRequired
