Repository lifinance/contracts, pull requests merged in 2025-07, with the labels that each got.

#1238 Redeploy GenericSwapFacetV3 with new native address on hyperevm
  config/networks.json
  deployments/_deployments_log_file.json
  deployments/hyperevm.diamond.json
  deployments/hyperevm.json
  script/deploy/resources/deployRequirements.json
  script/scriptMaster.sh
Labels: AuditNotRequired

#1218 LDA - Izumi and SyncSwap [ISyncSwapPool v1.0.0,ISyncSwapVault v1.0.0,IiZiSwapPool v1.0.0,LiFiDEXAggregator v1.11.0]
  audit/auditLog.json
  audit/reports/2025.06.30_LiFiDexAggregator(v1.11.0).pdf
  deployments/_deployments_log_file.json
  deployments/base.staging.json
  deployments/scroll.staging.json
  deployments/taiko.staging.json
  deployments/zksync.json
  src/Interfaces/ISyncSwapPool.sol
  src/Interfaces/ISyncSwapVault.sol
  src/Interfaces/IiZiSwapPool.sol
  src/Periphery/LiFiDEXAggregator.sol
  test/solidity/Periphery/LiFiDEXAggregator.t.sol
Labels: AuditCompleted, AuditRequired

#1240 deployed relay to celo & metis
  config/relay.json
  deployments/_deployments_log_file.json
  deployments/celo.diamond.json
  deployments/celo.json
  deployments/cronos.diamond.json
  deployments/cronos.json
  deployments/metis.diamond.json
  deployments/metis.json
  foundry.toml
  script/deploy/_targetState.json
  script/helperFunctions.sh
  script/tasks/diamondUpdateFacet.sh
Labels: AuditNotRequired

#1256 Deploy glacis to zksync & abstract
  config/glacis.json
  deployments/_deployments_log_file.json
  deployments/abstract.diamond.json
  deployments/abstract.json
  deployments/zksync.diamond.json
  deployments/zksync.json
  script/deploy/_targetState.json
  script/deploy/zksync/DeployGlacisFacet.zksync.s.sol
  script/deploy/zksync/DeployReceiverStargateV2.zksync.s.sol
  script/deploy/zksync/DeployStargateFacetV2.zksync.s.sol
  script/deploy/zksync/UpdateGlacisFacet.zksync.s.sol
  script/tasks/diamondUpdateFacet.sh
Labels: AuditNotRequired

#1248 Fix issue in log function
  script/helperFunctions.sh
Labels: AuditNotRequired

#1268 fix(okx): re-enable OKX and update SC
  config/dexs.json
Labels: AuditNotRequired

#1269 feat: add hyperbloom signature
  config/dexs.json
  config/sigs.json
Labels: AuditNotRequired

#1257 rollback to previous implementation (forward msg.value directly to diamond) [Permit2Proxy v1.0.4]
  audit/auditLog.json
  audit/reports/2025.07.06_Permit2Proxy(v1.0.4).pdf
  src/Periphery/Permit2Proxy.sol
Labels: AuditCompleted, AuditRequired

#1267 Improve DeployScriptbase log output
  archive/scripts/Deploy/DeployStandardizedCallFacet.s.sol
  script/deploy/facets/DeployCalldataVerificationFacet.s.sol
  script/deploy/facets/utils/DeployScriptBase.sol
  script/deploy/zksync/utils/DeployScriptBase.sol
Labels: AuditNotRequired

#1272 fix: add new OKX route SC address for coronos network
  config/dexs.json
Labels: AuditNotRequired

#1274 some improvements for deploy safe script
  script/deploy/safe/deploy-safe.ts
Labels: AuditNotRequired

#1253 Allow bun module in eslintrc rules
  .eslintrc.cjs
  bun.lock
  package.json
  script/deploy/healthCheck.ts
  tsconfig.eslint.json
Labels: AuditNotRequired

#1280 Revert: Add parameter validation to allbridge lf 14440 [GenericErrors v1.0.0,AllBridgeFacet v2.0.0,ChainflipFacet v1.0.0,RelayFacet v1.0.0,SwapperV2 v1.0.0,LibAsset v2.1.0,ReceiverChainflip v1.0.0]
  conventions.md
  docs/ChainflipFacet.md
  src/Errors/GenericErrors.sol
  src/Facets/AllBridgeFacet.sol
  src/Facets/ChainflipFacet.sol
  src/Facets/RelayFacet.sol
  src/Helpers/LiFiData.sol
  src/Helpers/SwapperV2.sol
  src/Libraries/LibAsset.sol
  src/Periphery/ReceiverChainflip.sol
  test/solidity/Facets/AllBridgeFacet.t.sol
  test/solidity/Facets/ChainflipFacet.t.sol
  test/solidity/Facets/RelayFacet.t.sol
  test/solidity/Periphery/LidoWrapper/LidoWrapper.t.sol
  test/solidity/Periphery/ReceiverChainflip.t.sol
Labels: AuditRequired

#1194 Improve docs, AI-related files etc.
  .cursorrules.example
  .gitignore
  .solhint.json
  README.md
  conventions.md
  docs/Deploy.md
  script/deploy/facets/DeployLiFiTimelockController.s.sol
  src/Facets/AcrossFacetPacked.sol
  src/Facets/AcrossFacetPackedV3.sol
  src/Facets/AcrossFacetV3.sol
  src/Facets/EmergencyPauseFacet.sol
  src/Facets/GasZipFacet.sol
  src/Facets/GenericSwapFacetV3.sol
  src/Facets/MayanFacet.sol
  src/Facets/PioneerFacet.sol
  src/Facets/SquidFacet.sol
  src/Facets/StargateFacetV2.sol
  src/Helpers/Validatable.sol
  src/Interfaces/IAcrossSpokePool.sol
  src/Interfaces/IConnextHandler.sol
  src/Interfaces/IGasZip.sol
  src/Interfaces/IGatewayRouter.sol
  src/Libraries/LibAsset.sol
  src/Libraries/LibBytes.sol
  src/Libraries/LibSwap.sol
  src/Libraries/OFTComposeMsgCodec.sol
  src/Periphery/GasZipPeriphery.sol
  src/Periphery/LiFiDEXAggregator.sol
  src/Periphery/LidoWrapper.sol
  src/Periphery/Permit2Proxy.sol
  src/Periphery/ReceiverAcrossV3.sol
  src/Periphery/ReceiverStargateV2.sol
  src/Periphery/TokenWrapper.sol
  src/Security/LiFiTimelockController.sol
Labels: WIP, AuditNotRequired

#1252 Added tsc-files for staged files
  package.json
Labels: AuditNotRequired

#1284 Deprecate old scripts needed for transition to Timelock ownership
  script/deploy/safe/propose-timelock-ownership.ts
  script/deploy/safe/schedule-confirm-timelock-ownership.ts
Labels: AuditNotRequired

#1288 drop old indexes if they exist and rereate with proper name
  script/deploy/update-deployment-logs.ts
Labels: AuditNotRequired

#1291 Enhancement/better safe tx fetching
  script/deploy/safe/confirm-safe-tx.ts
  script/deploy/safe/safe-utils.ts
Labels: AuditNotRequired

#1292 remove bun import from healthcheck
  script/deploy/healthCheck.ts
Labels: AuditNotRequired

#1225 Deploy network ronin
  .solhint.json
  config/dexs.json
  config/gaszip.json
  config/glacis.json
  config/networks.json
  config/permit2Proxy.json
  config/relay.json
  deployments/_deployments_log_file.json
  deployments/ronin.diamond.json
  deployments/ronin.json
  foundry.toml
  script/deploy/_targetState.json
  script/deploy/healthCheck.ts
  script/deploy/safe/confirm-safe-tx.ts
  script/deploy/safe/deploy-safe.ts
  script/deploy/update-deployment-logs.ts
  script/tasks/diamondUpdateFacet.sh
  test/solidity/Facets/AcrossFacetPacked.t.sol
  test/solidity/Facets/AcrossFacetPackedV3.t.sol
Labels: AuditNotRequired, NewNetwork

#1294 deployed PioneerFacet to OPT, ARB, Soneium
  deployments/_deployments_log_file.json
  deployments/arbitrum.diamond.json
  deployments/arbitrum.json
  deployments/optimism.diamond.json
  deployments/optimism.json
  deployments/soneium.diamond.json
  deployments/soneium.json
  script/helperFunctions.sh
Labels: AuditNotRequired
