Repository lifinance/contracts, pull requests merged in 2025-03, with the labels that each got.

#1035 LF-12472 - Updated discord to slack webhook
  script/config.example.sh
  script/helperFunctions.sh
  script/tasks/diamondEMERGENCYPause.sh
Labels: AuditNotRequired

#1037 adds test to CalldataVerificationFacet to address Olympix error
  test/solidity/Facets/CalldataVerificationFacet.t.sol
Labels: AuditNotRequired

#1025 LF-12515 Improved Solhint
  .solhint.json
  package.json
  yarn.lock
Labels: AuditNotRequired

#1041 Fixed solhint and CallDataVerificationFacet.t.sol
  .solhint.json
  test/solidity/Facets/CalldataVerificationFacet.t.sol
Labels: AuditNotRequired

#1039 fetch all pendings TXs at once
  script/deploy/safe/confirm-safe-tx.ts
Labels: AuditNotRequired

#1034 LF-12360 - Moved create3Factory addresses to networks.js and adjusted scripts
  config/global.json
  config/networks.json
  script/deploy/deploySingleContract.sh
  script/helperFunctions.sh
Labels: AuditNotRequired

#1015 improve SAFE ownership and threshold change script
  package.json
  script/deploy/safe/add-owners-to-safe.ts
  script/deploy/safe/add-safe-owners-and-threshold.ts
  script/utils/viemScriptHelpers.ts
Labels: AuditNotRequired

#1040 LF-12584 - Added conventions.md
  conventions.md
Labels: AuditNotRequired

#945 LF-11761 - Implement glacis [GlacisFacet v1.0.0,IGlacisAirlift v1.0.0]
  audit/auditLog.json
  audit/reports/2025.02.19_GlacisFacet(v1.0.0).pdf
  config/glacis.json
  deployments/_deployments_log_file.json
  deployments/arbitrum.diamond.staging.json
  deployments/arbitrum.staging.json
  docs/GlacisFacet.md
  script/demoScripts/demoGlacis.ts
  script/deploy/facets/DeployGlacisFacet.s.sol
  script/deploy/facets/UpdateGlacisFacet.s.sol
  src/Facets/GlacisFacet.sol
  src/Interfaces/IGlacisAirlift.sol
  templates/facetDemoScript.template.hbs
  test/solidity/Facets/GlacisFacet.t.sol
  test/solidity/utils/Interfaces.sol
  test/solidity/utils/TestBase.sol
Labels: AuditCompleted, waitForAudit, AuditRequired

#985 LF-12061 Run healthcheck on new network
  .github/workflows/healthCheckForNewNetworkDeployment.yml
  script/deploy/healthCheck.ts
Labels: AuditNotRequired

#1043 Fix solhint rules and adjusted GlacisFacet test file
  .solhint.json
  test/solidity/Facets/GlacisFacet.t.sol
Labels: AuditNotRequired

#1032 Add new function selectors to MayanFacet [MayanFacet v1.1.0]
  audit/auditLog.json
  audit/reports/2025.02.28_MayanFacet(v1.1.0).pdf
  deployments/_deployments_log_file.json
  deployments/arbitrum.diamond.json
  deployments/arbitrum.diamond.staging.json
  deployments/arbitrum.json
  deployments/arbitrum.staging.json
  deployments/avalanche.diamond.json
  deployments/avalanche.json
  deployments/base.diamond.json
  deployments/base.json
  deployments/bsc.diamond.json
  deployments/bsc.json
  deployments/mainnet.diamond.json
  deployments/mainnet.json
  deployments/optimism.diamond.json
  deployments/optimism.json
  deployments/polygon.diamond.json
  deployments/polygon.json
  src/Facets/MayanFacet.sol
  test/solidity/Facets/MayanFacet.t.sol
Labels: AuditCompleted, AuditRequired

#1045 Convert DISMISS_COMMENT to single line
  .github/workflows/securityAlertsReview.yml
Labels: AuditNotRequired

#1022 Deprecate unused interfaces & split Stargate config files (V1, V2)
  archive/src/Interfaces/IDeBridgeGate.sol
  archive/src/Interfaces/IHyphenRouter.sol
  archive/src/Interfaces/IMultichainRouter.sol
  archive/src/Interfaces/IMultichainToken.sol
  archive/src/Interfaces/IStargateRouter.sol
  archive/src/Interfaces/ISynapseRouter.sol
  archive/src/Interfaces/ITeleportGateway.sol
  archive/src/Interfaces/ITokenMessenger.sol
  archive/src/Interfaces/ITransactionManager.sol
  config/stargateV2.json
  script/demoScripts/demoStargateV2Tx.ts
  script/deploy/facets/DeployReceiverStargateV2.s.sol
  script/deploy/facets/DeployStargateFacetV2.s.sol
  script/deploy/resources/deployRequirements.json
  script/deploy/zksync/DeployReceiverStargateV2.s.sol
  script/deploy/zksync/DeployStargateFacetV2.s.sol
Labels: AuditNotRequired

#1051 config: add dex and sigs for superswap ink
  config/dexs.json
Labels: AuditNotRequired

#1046 LF-12584 - conventions.md
  conventions.md
Labels: AuditNotRequired

#1055 Removed mocharc.js and _scripts.js
  .mocharc.js
  _scripts.js
Labels: AuditNotRequired

#1056 Added checkNetworksJsonFilePath
  script/deploy/deployFacetAndAddToDiamond.sh
  script/helperFunctions.sh
  script/scriptMaster.sh
  script/tasks/acceptOwnershipTransferPeriphery.sh
  script/tasks/checkExecutorAndReceiver.sh
  script/tasks/diamondEMERGENCYPause.sh
  script/tasks/diamondSyncDEXs.sh
  script/tasks/diamondSyncSigs.sh
  script/tasks/diamondUpdatePeriphery.sh
  script/tasks/diamondUpdateSgConfig.sh
  script/tasks/updateFacetConfig.sh
  script/utils/diamondEMERGENCYPauseGitHub.sh
Labels: AuditNotRequired

#1053 audit verifier adjusted to exclude comments and interface files
  .github/workflows/versionControlAndAuditCheck.yml
Labels: AuditNotRequired

#1061 mainnet whitelist okx address updated
  config/dexs.json
Labels: AuditNotRequired

#1060 deployed mayan to unichain
  config/mayan.json
  deployments/_deployments_log_file.json
  deployments/unichain.diamond.json
  deployments/unichain.json
Labels: AuditNotRequired

#1065 LF-12631 mayanfacet tests
  script/demoScripts/demoMayan.ts
  test/solidity/Facets/MayanFacet.t.sol
Labels: AuditNotRequired

#1064 adds pagination to git actions
  .github/workflows/ensureSCCoreDevApproval.yml
  .github/workflows/protectSecurityRelevantCode.yml
Labels: AuditNotRequired

#1068 Fix chainflip solhint, updated facetUpdateScript
  script/deploy/facets/UpdateChainflipFacet.s.sol
  src/Facets/ChainflipFacet.sol
  src/Periphery/ReceiverChainflip.sol
  templates/facetUpdateScript.template.hbs
Labels: AuditNotRequired

#953 LF-11894 zkevm update scripts
  .gitignore
  config/networks.json
  foundry.toml
  script/deploy/deploySingleContract.sh
  script/deploy/zksync/UpdateRelayFacet.zksync.s.sol
  script/deploy/zksync/utils/ScriptBase.sol
  script/deploy/zksync/utils/UpdateScriptBase.sol
  script/deploy/zksync/utils/contract-selectors.sh
  script/helperFunctions.sh
  script/scriptMaster.sh
  script/tasks/diamondUpdateFacet.sh
Labels: AuditNotRequired

#1050 Remove reliance on SAFE SDKs
  package.json
  script/deploy/safe/add-safe-owners-and-threshold.ts
  script/deploy/safe/config.ts
  script/deploy/safe/confirm-safe-tx.ts
  script/deploy/safe/propose-to-safe.ts
  script/deploy/safe/safe-decode-utils.ts
  script/deploy/safe/safe-utils.ts
  yarn.lock
Labels: AuditNotRequired

#1047 Added solhint ignores
  src/Facets/GlacisFacet.sol
  src/Facets/MayanFacet.sol
Labels: AuditNotRequired

#1073 Fix safe signing issues
  script/deploy/safe/confirm-safe-tx.ts
  script/deploy/safe/safe-utils.ts
Labels: AuditNotRequired

#1074 networks file removed
  networks
Labels: AuditNotRequired

#1076 Deploy glacis to prod
  config/glacis.json
  deployments/_deployments_log_file.json
  deployments/arbitrum.diamond.json
  deployments/arbitrum.json
  deployments/avalanche.diamond.json
  deployments/avalanche.json
  deployments/base.diamond.json
  deployments/base.json
  deployments/bsc.diamond.json
  deployments/bsc.json
  deployments/linea.diamond.json
  deployments/linea.json
  deployments/mainnet.diamond.json
  deployments/mainnet.json
  deployments/mode.diamond.json
  deployments/mode.json
  deployments/optimism.diamond.json
  deployments/optimism.json
  deployments/polygon.diamond.json
  deployments/polygon.json
  deployments/scroll.diamond.json
  deployments/scroll.json
  script/scriptMaster.sh
Labels: AuditNotRequired

#1077 Fixed no lintable files for solhint
  package.json
Labels: AuditNotRequired

#1067 Archive AmarokFacet
  .solhintignore
  archive/src/Facets/AmarokFacet.sol
Labels: AuditNotRequired
