Repository lifinance/contracts, pull requests merged in 2025-08, with the labels that each got.

#1258 Deploy LDA 1.11.0 (izumi/syncSwap) to various chains
  config/dexs.json
  config/gaszip.json
  config/networks.json
  deployments/_deployments_log_file.json
  deployments/arbitrum.json
  deployments/aurora.diamond.json
  deployments/aurora.json
  deployments/base.diamond.json
  deployments/base.json
  deployments/blast.diamond.json
  deployments/blast.json
  deployments/bob.diamond.json
  deployments/bob.json
  deployments/bsc.diamond.json
  deployments/bsc.json
  deployments/cronos.diamond.json
  deployments/cronos.json
  deployments/gravity.diamond.json
  deployments/gravity.json
  deployments/linea.diamond.json
  deployments/linea.json
  deployments/mainnet.diamond.json
  deployments/mainnet.json
  deployments/mantle.diamond.json
  deployments/mantle.json
  deployments/mode.json
  deployments/plume.diamond.json
  deployments/plume.json
  deployments/polygon.diamond.json
  deployments/polygon.json
  deployments/scroll.diamond.json
  deployments/scroll.json
  deployments/taiko.diamond.json
  deployments/taiko.json
  deployments/xlayer.diamond.json
  deployments/xlayer.json
  deployments/zksync.diamond.json
  deployments/zksync.json
  script/helperFunctions.sh
Labels: AuditNotRequired

#1124 Integrate Patcher [Patcher v1.0.0]
  audit/auditLog.json
  audit/reports/2025.07.30_Patcher(v1.0.0).pdf
  bun.lock
  deployments/_deployments_log_file.json
  deployments/arbitrum.diamond.staging.json
  deployments/arbitrum.staging.json
  deployments/base.staging.json
  docs/Patcher.md
  docs/README.md
  package.json
  script/demoScripts/demoPatcher.ts
  script/demoScripts/demoPatcherDest.ts
  script/demoScripts/utils/cowSwapHelpers.ts
  script/demoScripts/utils/patcherHelpers.ts
  script/deploy/facets/DeployPatcher.s.sol
  src/Periphery/Patcher.sol
  test/solidity/Periphery/Patcher.t.sol
Labels: AuditCompleted, waitForAudit, AuditRequired

#1306 parallelize timelock proposal execution script
  script/deploy/safe/execute-pending-timelock-tx.ts
Labels: AuditNotRequired

#1317 Fix ESLint issues in demoPatcher scripts
  script/demoScripts/demoPatcherDest.ts
  script/demoScripts/utils/cowSwapHelpers.ts
Labels: AuditNotRequired

#1320 config: whitelist new OKX contract
  config/dexs.json
Labels: AuditNotRequired

#1316 Deploy sophon chain
  config/dexs.json
  config/gaszip.json
  config/networks.json
  config/permit2Proxy.json
  config/stargateV2.json
  deployments/_deployments_log_file.json
  deployments/sophon.diamond.json
  deployments/sophon.json
  foundry.toml
  script/common/types.ts
  script/deploy/_targetState.json
  script/deploy/deployAllContracts.sh
  script/deploy/deploySingleContract.sh
  script/deploy/facets/UpdateCoreFacets.s.sol
  script/deploy/healthCheck.ts
  script/deploy/zksync/UpdateCoreFacets.zksync.s.sol
  script/deploy/zksync/UpdateStargateFacetV2.zksync.s.sol
  script/helperFunctions.sh
Labels: AuditNotRequired

#1323 feat: add bebop approval manager address to whitelist
  config/dexs.json
Labels: AuditNotRequired

#1308 add receiverAddress parameter to GlacisFacet [GlacisFacet v1.1.0]
  audit/auditLog.json
  audit/reports/2025.08.22_GlacisFacet(v1.1.0).pdf
  deployments/_deployments_log_file.json
  deployments/arbitrum.diamond.staging.json
  deployments/arbitrum.staging.json
  deployments/base.staging.json
  deployments/optimism.diamond.staging.json
  deployments/optimism.staging.json
  docs/GlacisFacet.md
  script/demoScripts/demoGlacis.ts
  script/demoScripts/utils/demoScriptHelpers.ts
  src/Facets/GlacisFacet.sol
  test/solidity/Facets/GlacisFacet.t.sol
Labels: WIP, waitForBackend, AuditCompleted, AuditRequired

#1335 remove duplicate address from dexs.json
  config/dexs.json
Labels: AuditNotRequired

#1303 Tron deployments
  .github/workflows/networkRpcsChecker.yml
  bun.lock
  config/allbridge.json
  config/networks.json
  config/symbiosis.json
  deployments/_deployments_log_file.json
  deployments/tron.diamond.json
  deployments/tron.json
  deployments/tronshasta.json
  package.json
  script/deploy/_targetState.json
  script/deploy/healthCheck.ts
  script/deploy/tron/TronContractDeployer.ts
  script/deploy/tron/constants.ts
  script/deploy/tron/deploy-and-register-allbridge-facet.ts
  script/deploy/tron/deploy-and-register-periphery.ts
  script/deploy/tron/deploy-and-register-symbiosis-facet.ts
  script/deploy/tron/deploy-core-facets.ts
  script/deploy/tron/register-facets-to-diamond.ts
  script/deploy/tron/types.ts
  script/deploy/tron/utils.ts
  script/helperFunctions.sh
  script/mongoDb/fetch-rpcs.ts
  script/troncast/README.md
  script/troncast/commands/call.ts
  script/troncast/commands/send.ts
  script/troncast/index.ts
  script/troncast/postinstall-tronweb-fix.mjs
  script/troncast/types.ts
  script/troncast/utils/abi.ts
  script/troncast/utils/formatter.ts
  script/troncast/utils/parser.ts
  script/troncast/utils/tronweb.ts
  script/utils/diamondEMERGENCYPauseGitHub.sh
  script/utils/network.ts
  tsconfig.json
Labels: AuditNotRequired

#1331 Improve verification helper
  config/networks.json
  foundry.toml
  script/helperFunctions.sh
Labels: AuditNotRequired

#1337 feat: Whitelist Hypertrade sc and signature
  config/dexs.json
  config/sigs.json
Labels: AuditNotRequired

#1322 LF-14930 Mayan Hypercore Route [MayanFacet v1.2.2]
  audit/auditLog.json
  audit/reports/2025.08.25_MayanFacet(v1.2.2).pdf
  deployments/_deployments_log_file.json
  deployments/base.diamond.staging.json
  deployments/base.staging.json
  deployments/optimism.diamond.staging.json
  deployments/optimism.staging.json
  src/Facets/MayanFacet.sol
  test/solidity/Facets/MayanFacet.t.sol
Labels: AuditCompleted, AuditRequired

#1283 LF-14567 Add KatanaV3 to LDA [IKatanaV3AggregateRouter v1.0.0,IKatanaV3Governance v1.0.0,IKatanaV3Pool v1.0.0,LibAsset v2.1.2,LiFiDEXAggregator v1.12.0]
  .github/workflows/versionControlAndAuditCheck.yml
  audit/auditLog.json
  audit/reports/2025.07.28_LiFiDexAggregator(v1.12.0).pdf
  config/dexs.json
  deployments/_deployments_log_file.json
  deployments/ronin.diamond.json
  deployments/ronin.json
  src/Interfaces/KatanaV3/IKatanaV3AggregateRouter.sol
  src/Interfaces/KatanaV3/IKatanaV3Governance.sol
  src/Interfaces/KatanaV3/IKatanaV3Pool.sol
  src/Libraries/LibAsset.sol
  src/Periphery/LiFiDEXAggregator.sol
  test/solidity/Facets/ChainflipFacet.t.sol
  test/solidity/Periphery/LiFiDEXAggregator.t.sol
Labels: AuditCompleted, AuditRequired

#1325 add token contract checks for newly added addresses in dexs.json
  foundry.toml
  script/tasks/diamondSyncDEXs.sh
Labels: AuditNotRequired

#1341 re-deployed glacisFacet v1.0.0 to ronin
  deployments/_deployments_log_file.json
  deployments/ronin.diamond.json
  deployments/ronin.json
Labels: AuditNotRequired

#1342 remove urls from README
  script/troncast/README.md
Labels: AuditNotRequired

#1136 redeployed TokenWrapper on Fraxtal with new wrappedNative adddress
  config/dexs.json
  config/networks.json
  deployments/_deployments_log_file.json
  deployments/fraxtal.diamond.json
  deployments/fraxtal.json
  script/deploy/tron/utils.ts
Labels: waitForBackend, AuditNotRequired
